openapi: 3.0.0
info:
  title: API de Usuarios
  version: 1.0.0

paths:
  /api/products/all-products:
    get:
      summary: Obtener todos los productos.
      tags:
        - Products
      responses:
        '200':
          description: Respuesta exitosa
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#components/schemas/Products'
        '500':
          description: Error interno del servidor

  /api/products/:
    post:
      summary: Agrega un nuevo producto
      tags:
        - Products
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#components/requesBodies/DataProduct'
      responses:
        '201':
          description: Respuesta exitosa
          content:
            application/json:
              schema:
                $ref: '#components/schemas/Products'
        '404':
          description: Usuario no encontrado
        '500':
          description: Error interno del servidor

  /api/products/{uid}:
    get:
      summary: Obtener un usuario por su ID.
      tags:
        - Products
      parameters:
        - name: uid
          in: path
          required: true
          description: ID del producto a buscar
          schema:
            type: string
      responses:
        '200':
          description: Respuesta exitosa
          content:
            application/json:
              schema:
                $ref: '#components/schemas/Products'
        '404':
          description: Usuario no encontrado
        '500':
          description: Error interno del servidor   
    put:
      summary: actualiza el producto
      tags:
        - Products
      parameters:
      - name: uid
        in: path
        required: true
        description: Id del producto para actualizar
        schema:
          $type: String
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#components/requesBodies/DataProduct'
      responses:
        '201':
          description: Respuesta exitosa
          content:
            application/json:
              schema:
                $ref: '#components/schemas/Products'
        '404':
          description: Usuario no encontrado
        '500':
          description: Error interno del servidor
    delete:
      summary: borra un producto
      tags:
        - Products
      parameters:
        - name: uid
          in: path
          required: true
          description: ID del producto a buscar
          schema:
            type: string
      responses:
        '201':
          description: Respuesta exitosa
          content:
            application/json:
              schema:
                $ref: '#components/schemas/Products'
        '404':
          description: Usuario no encontrado
        '500':
          description: Error interno del servidor