openapi: 3.0.0
info:
  title: API de Usuarios
  version: 1.0.0

paths:
  /api/account/user:
    get:
      summary: Obtener todos los usuarios.
      tags:
        - Users
      responses:
        '200':
          description: Respuesta exitosa
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#components/schemas/Users'
        '500':
          description: Error interno del servidor

  /api/account/user/{uid}:
    get:
      summary: Obtener un usuario por su ID.
      tags:
        - Users
      parameters:
        - name: uid
          in: path
          required: true
          description: ID del usuario a buscar
          schema:
            type: string
      responses:
        '200':
          description: Respuesta exitosa
          content:
            application/json:
              schema:
                $ref: '#components/schemas/Users'
        '404':
          description: Usuario no encontrado
        '500':
          description: Error interno del servidor