openapi: 3.0.0
info:
  title: API de Usuarios
  version: 1.0.0

paths:
  /api/carts/:
    get:
      summary: Obtener todos los carritos de los usuarios.
      tags:
        - Carts
      responses:
        '200':
          description: Respuesta exitosa
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#components/schemas/Carts'
        '500':
          description: Error interno del servidor
          
  /api/carts/{uid}:
    get:
      summary: Obtener los datos de los productos del carrito.
      tags:
        - Carts
      parameters:
        - name: uid
          in: path
          required: true
          description: ID del carrito a buscar
          schema:
            type: string
      responses:
        '200':
          description: Respuesta exitosa
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#components/schemas/CartPopulate'
        '404':
          description: Error carrito id no encontrado
        '500':
          description: Error interno del servidor
    put:
      summary: Actualiza el carrito a gusto
      tags:
        - Carts
      parameters:
      - name: uid
        in: path
        required: true
        description: Id del carrito a actualizar
        schema:
          $type: String
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#components/schema/CartPopulate'
      responses:
        '201':
          description: Respuesta exitosa
          content:
            application/json:
              schema:
                $ref: '#components/schemas/CartPopulate'
        '404':
          description: Error carrito id no encontrado
        '500':
          description: Error interno del servidor
    delete:
      summary: Borra todo el carrito
      tags:
        - Carts
      parameters:
        - name: uid
          in: path
          required: true
          description: ID del carrito a borrar
          schema:
            type: string
      responses:
        '201':
          description: Respuesta exitosa
          content:
            application/json:
              schema:
                $ref: '#components/schemas/CartPopulate'
        '404':
          description: Error carrito id no encontrado
        '500':
          description: Error interno del servidor
  
  /api/carts/{uid}/products/{pid}:
    get:
      summary: Obtener los datos de los productos del carrito.
      tags:
        - Carts
      parameters:
        - name: uid
          in: path
          required: true
          description: ID del carrito a buscar
          schema:
            type: string
      responses:
        '200':
          description: Respuesta exitosa
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#components/schemas/CartPopulate'
        '404':
          description: Error carrito id no encontrado
        '500':
          description: Error interno del servidor
    put:
      summary: Actualiza el carrito a gusto
      tags:
        - Carts
      parameters:
      - name: uid
        in: path
        required: true
        description: Id del carrito a actualizar
        schema:
          $type: String
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#components/schema/CartPopulate'
      responses:
        '201':
          description: Respuesta exitosa
          content:
            application/json:
              schema:
                $ref: '#components/schemas/CartPopulate'
        '404':
          description: Error carrito id no encontrado
        '500':
          description: Error interno del servidor
    delete:
      summary: Borra todo el carrito
      tags:
        - Carts
      parameters:
        - name: uid
          in: path
          required: true
          description: ID del carrito a borrar
          schema:
            type: string
      responses:
        '201':
          description: Respuesta exitosa
          content:
            application/json:
              schema:
                $ref: '#components/schemas/CartPopulate'
        '404':
          description: Error carrito id no encontrado
        '500':
          description: Error interno del servidor